apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-splitter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - splitwisemini.azurewebsites.net
    secretName: expense-splitter-tls
  rules:
  - host: splitwisemini.azurewebsites.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: expense-splitter
            port:
              number: 80
